FROM python:3.10-slim

WORKDIR /app

COPY pipeline_prepare_for_embedding.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "pipeline_prepare_for_embedding.py"]
